[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", "blueprint.json", "blueprint.lock", ".github/workflows/verify-template.yml"]

[placeholders.gh-username]
type = "string"
prompt = "Your GitHub username (or organization)"
# The username cannot end with a hyphen, too, but
# this requirement is not captured by the regex at the moment.
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[hooks]
pre = ["hooks/pre.rhai"]