[package]
name = "wsts-blueprint"
version = "0.1.0"
description = "A WSTS Blueprint that can run keygen and signing jobs on demand from the Tangle network"
edition = "2021"

[package.metadata.blueprint]
manager = { Evm = "WstsBlueprint" }

[dependencies]
gadget-sdk = { git = "https://github.com/tangle-network/gadget/", features = ["std"] }
#gadget-sdk = { path = "../gadget/sdk", features = ["std"] }
color-eyre = { version = "0.6", features = ["tracing-error", "color-spantrace"] }
tokio = { version = "1.40", default-features = false, features = ["full"] }
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.13.3", default-features = false }
bincode = "1.3.3"
sp-core = { version = "31.0.0", default-features = false }
rand_chacha = "0.3.1"
serde = { version = "1.0.214", features = ["derive"] }
round-based = { version = "0.3.2", features = ["runtime-tokio"] }
tracing-subscriber = "0.3.18"
thiserror = "2.0.3"
itertools = "0.13.0"
rand = "0.8.5"
parking_lot = { version = "0.12.3", features = ["serde"]}

# MPC specific deps
wsts = "3.0.0"

[build-dependencies]
blueprint-metadata = { git = "https://github.com/tangle-network/gadget/" }

[dev-dependencies]
blueprint-test-utils = { git = "https://github.com/tangle-network/gadget/" }
cargo-tangle = { git = "https://github.com/tangle-network/gadget/" }

[features]
default = ["std"]
std = []
