[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
auto_detect_remappings = true

[dependencies]
forge-std = "1.9.4"
tnt-core = "0.1.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
