[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
auto_detect_remappings = true

[dependencies]
forge-std = "1.9.4"
tnt-core = { version = "0.1.0", git = "https://github.com/tangle-network/tnt-core.git", rev = "df6d5d6da3c82217405c408d3c0b11369bb3e5c2" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
