name: Foundry CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: forge-validation-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  foundry-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Solidity Dependencies
        run: forge soldeer update -d

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --color always
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --color always
        id: test
